name: VERSION for release

on:
  push

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          yarn install
          yarn env:dev && yarn build

      - uses: go-semantic-release/action@v1
        id: semrel
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          update-file: package.json
          dry: true
          force-bump-patch-version: true
          custom-arguments: '--no-ci'
          changelog-generator-opt: 'emojis=true'

      - uses: go-semantic-release/action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          update-file: package.json
          force-bump-patch-version: true
          custom-arguments: '--no-ci'
          changelog-generator-opt: 'emojis=true'
